# Run with:
# ansible-playbook InstallLibJSonCpp.yml

---
- name: Install LibJSonCpp
  hosts: all
  tasks:

  - name: Install LibJSonCpp package on OpenSUSE/SUSE Linux
    zypper:
      name: libjsoncpp26
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install LibJSonCpp package on Raspberian Linux
    apt:
      name: libjsoncpp26
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1

