# Run with
# ansible-playbook SetupForgejo.yml
# https://forgejo.org/

---
- name: Setup Forgejo
  hosts: all
  tasks:

  - name: Create directory for data
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /opt/DockerSwarmData/forgejo
      - /root/docker
      - /root/docker/forgejo

  - name: Copy the docker-compose file with owner and permissions
    ansible.builtin.copy:
      src: docker-compose.yml
      dest: /root/docker/forgejo
      owner: ajorians
      group: users
      mode: 0777

  - name: Deploy Forgejo from a compose file
    community.docker.docker_compose_v2:
      project_src: /root/docker/forgejo

  - name: Make Apache VHost file
    ansible.builtin.copy:
      dest: /etc/apache2/vhosts.d/forgejo.conf
      force: false
      content: |
        <VirtualHost *:80>
          ServerName forgejo.orians.org
          ServerAlias forgejo.stage.orians.org forgejo
          ProxyPass / http://127.0.0.1:3000/
          ProxyPassReverse / http://127.0.0.1:3000/
        </VirtualHost>
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1
    notify:
    - Restart Apache2 service

  - name: Make Apache VHost file
    ansible.builtin.copy:
      dest: /etc/apache2/sites-available/forgejo.conf
      force: false
      content: |
        <VirtualHost *:80>
          ServerName forgejo.orians.org
          ServerAlias forgejo.stage.orians.org forgejo
          ProxyPass / http://127.0.0.1:3000/
          ProxyPassReverse / http://127.0.0.1:3000/
        </VirtualHost>
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1
    notify:
    - Restart Apache2 service

  handlers:
    - name: Restart Apache2 service
      ansible.builtin.systemd:
        state: restarted
        name: apache2

